name: Deploy terraform

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-west-2
    steps: 
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Deploy terraform
        run: |
          sh upload2s3.sh
          cd terraform
          terraform init
          terraform apply -auto-approve
      - name: terminate oldest instance
        run: |
         aws autoscaling update-auto-scaling-group --auto-scaling-group-name terraform-20221102180649199600000002 --termination-policies "OldestInstance"             
